### ISSUE TITLE
Latest rundeck 4.6.1 : Invalid API Request

### ISSUE THREAD

**Issue by halradaideh** [phsmith/rundeck_exporter#57]
the latest exporter has an issue with the latest rundeck 4.6.1

2022-09-17 06:19:46,940 - CRITICAL - Invalid API Request: /api/34/metrics/metrics

**Comment by phsmith** [comment]
Hey @halradaideh , sorry for the late response.
I checked it out and the problem is that since version 4.x.x Rundeck disabled by default the metrics endpoint, so you need to enable it to get the exporter to work again.
See: https://docs.rundeck.com/docs/administration/configuration/config-file-reference.html#metrics-capturing

**Comment by halradaideh** [comment]
cool thanks
